Fixed AttributeError: module 'cinder.volume.driver' has no attribute 'ExtendVD'
Based on upstream commit:

    commit 2c8b3d457d903d1f3ab98311d9d5371e5a5c0ecd
    Author: Ivan Kolodyazhny <e0ne@e0ne.info>
    Date:   Fri Sep 15 10:34:41 2017 -0600

        Remove deprecated VD base classes which are not used now

        Change-Id: I171022c0af01f4216c30630be7487f6f53d5fbca